NDefines.NGame.START_DATE = "1857.5.10.24" -- "1936.1.1.12"
NDefines.NGame.END_DATE = "2100.1.1.1" -- "1949.1.1.1"
NDefines.NGame.HANDS_OFF_START_TAG = "UCT" --URG

NDefines.NDiplomacy.MAX_TRUST_VALUE = 80 -- 100
NDefines.NDiplomacy.MIN_TRUST_VALUE = -80 -- -100
NDefines.NDiplomacy.MAX_OPINION_VALUE = 200 -- 100
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200 -- -100
NDefines.NDiplomacy.BASE_TRUCE_PERIOD = 30 -- 180
NDefines.NDiplomacy.PEACE_INCREASE_COST_FACTOR_PER_MISSING_PERCENT_FOR_CAPITULATION = 0.01 -- 0.002
NDefines.NDiplomacy.INFLUENCE_RATIO_CAPITAL = 0.3 -- 0.2
NDefines.NDiplomacy.INFLUENCE_RATIO_CONTROLLED = 0.4 -- 0.5
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1857.5.10.24" -- "1936.1.1.12"
-- NDefines.NDiplomacy.INFLUENCE_REDUCTION_PER_CAPITAL_DIST = 0.05 -- depreciated 1.12.5
-- NDefines.NDiplomacy.INFLUENCE_REDUCTION_PER_CORE_DIST = 0.05 -- depreciated 1.12.5
-- NDefines.NDiplomacy.INFLUENCE_REDUCTION_PER_CONTROLLED_DIST = 0.10 -- depreciated 1.12.5
-- NDefines.NDiplomacy.INFLUENCE_MAX_DISCOUNT = 0.25  -- depreciated 1.12.5
NDefines.NDiplomacy.BASE_IMPROVE_RELATION_COST = 20 -- 10
NDefines.NDiplomacy.BASE_IMPROVE_RELATION_SAME_IDEOLOGY_GROUP_MAINTAIN_COST = 0.15 -- 0.20
NDefines.NDiplomacy.BASE_IMPROVE_RELATION_DIFFERENT_IDEOLOGY_GROUP_MAINTAIN_COST = 0.3 --0.4
NDefines.NDiplomacy.PEACE_SCORE_SCALE_FACTOR = 1.25 -- 1.35
NDefines.NCountry.STATE_VALUE_MANPOWER_FACTOR = 0.15 --0.1
NDefines.NCountry.AIR_SUPPLY_CONVERSION_SCALE = 0.001 -- 0.002

-- NDefines.NProduction.PRODUCTION_RESOURCE_LACK_PENALTY = -0.50 -- 0.05

-- NDefines.NTechnology.BASE_TECH_COST = 1000 -- 100

-- NDefines.NBuildings.MAX_SHARED_SLOTS = 81 -- 25

-- NDefines.NMilitary.WAR_SCORE_PROVINCE_FACTOR = 0.3 -- 2.0
-- NDefines.NMilitary.WAR_SCORE_LEND_LEASE_GIVEN_IC_FACTOR = 0.1 -- 0.001
-- NDefines.NMilitary.WAR_SCORE_LEND_LEASE_GIVEN_FUEL_FACTOR = 0.01 -- 0.001
-- NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_IC_FACTOR = 0.1 -- 0.001
-- NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_FUEL_FACTOR = 0.01 -- 0.001
-- NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.1 -- 0.4

-- NDefines.NAir.TOP_SPEED_DAMAGE_BONUS_FACTOR = 0.02 -- 0.025
-- NDefines.NAir.COMBAT_BETTER_SPEED_DAMAGE_INCREASE = 0.45 -- 0.60
-- NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.25 -- 1.0
-- NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 1 -- 5.0
-- NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_STR = 2.0 -- 1.0
-- NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 2.5 -- 1.5

-- NDefines.NAir.THRUST_WEIGHT_SPEED_FACTOR = 6 -- 3

-- NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.02 -- 0.001
-- NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.04 -- 0.004
-- NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_CONVOY = 10.0 -- 0.05
-- NDefines.NNavy.WAR_SCORE_DECAY_FOR_BUILT_CONVOY = 5.0 -- 0.03
-- NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO = 0.2 -- 0.25
-- NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE = 0.2 -- 0.25
-- NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.15 -- 0.2
-- NDefines.NNavy.HIT_PROFILE_MULT = 50.0 -- 100
-- NDefines.NNavy.HIT_PROFILE_SPEED_FACTOR = 0.5 -- 2

-- NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_LAND = 10 -- 50
-- NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 20 -- 25

-- NDefines.NFocus.FOCUS_POINT_DAYS = 1 -- 7
